spring:
   datasource:
     schema: classpath:database-initialize.sql
     name: dev
     url: jdbc:mysql://127.0.0.1:3306/frp?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
     username: root
     password: ENC(SrpFBcVD89eTQ2icOD0TMg==)
     # 使用druid数据源
     ##type: com.mchange.v2.c3p0.ComboPooledDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
     filters: stat
     maxActive: 20
     initialSize: 1
     maxWait: 60000
     minIdle: 1
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxOpenPreparedStatements: 20

logging:
  level:
     root: info
     org:
       springframework: warn
       hibernate: warn
       eclipse: warn
       apache: warn
     com:
       weasel: info
  file: "logs/application.log"
